# Propiedades de SonarQube para el proyecto Frontend (Angular)
sonar.projectKey=EcoLand-Frontend
sonar.projectName=EcoLand - Frontend
sonar.projectVersion=1.0

# Ruta a las fuentes
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.ts, src/environments/**

# Lenguajes
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

# Codificación
sonar.sourceEncoding=UTF-8

# (Opcional) Si en el futuro agregas reportes de cobertura:
# sonar.typescript.lcov.reportPaths=coverage/lcov.info
