# Propiedades unificadas de SonarQube para el proyecto EcoLand (Monorepo)
sonar.projectKey=EcoLand
sonar.projectName=EcoLand - Sistema Integrado
sonar.projectVersion=1.0

# Definición de módulos
sonar.modules=backend,frontend

# Configuración del módulo Backend
backend.sonar.projectName=EcoLand Backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main/java
# Importante para que Java no dé errores de resolución:
backend.sonar.java.binaries=target/classes

# Configuración del módulo Frontend
frontend.sonar.projectName=EcoLand Frontend
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**, **/*.spec.ts, src/environments/**
frontend.sonar.typescript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.sourceEncoding=UTF-8
